name: Build Psiphon Tunnel Core

on:
  workflow_dispatch:
  
  schedule:
  - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
    
      ####################################################################
      # Get latest upstream commit
      ####################################################################
    
      - name: Get latest upstream SHA
        id: upstream
        run: |
          SHA=$(git ls-remote https://github.com/Psiphon-Labs/psiphon-tunnel-core.git HEAD | cut -f1)
    
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "short_sha=${SHA:0:7}" >> $GITHUB_OUTPUT
    
      ####################################################################
      # Skip if release already exists
      ####################################################################
    
      - name: Check release existence
        id: release_check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="upstream-${{ steps.upstream.outputs.sha }}"
          LATEST_TAG=$(gh release view --json tagName --jq .tagName)
          echo "latest_compiled_commit=${LATEST_TAG:9:7}" >> $GITHUB_OUTPUT
    
          if gh release view "$TAG" >/dev/null 2>&1
          then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
    
      - name: Exit if already built
        if: steps.release_check.outputs.exists == 'true'
        run: |
          echo "Release already exists."
          exit 0
    
      ####################################################################
      # Clone upstream
      ####################################################################
    
      - name: Clone upstream repository
        id: clone_upstream_repository
        if: steps.release_check.outputs.exists == 'false'
        run: |
          git clone https://github.com/Psiphon-Labs/psiphon-tunnel-core.git src
          cd src
          git checkout ${{ steps.upstream.outputs.sha }}
          echo "git_log=\"$(git log --format='%h: %s' ${{ steps.release_check.outputs.latest_compiled_commit }}..${{ steps.upstream.outputs.sha }})\"" >> $GITHUB_OUTPUT
    
      ####################################################################
      # Setup Go
      ####################################################################
    
      - name: Setup Go
        if: steps.release_check.outputs.exists == 'false'
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
    
      ####################################################################
      # Build binaries
      ####################################################################
    
      - name: Build binaries
        if: steps.release_check.outputs.exists == 'false'
        run: |
          mkdir -p dist
          cd src
          build() {
    
            GOOS="$1"
            GOARCH="$2"
            ARCHNAME="$3"
    
            OUT="../dist/psiphon-tunnel-core-${GOOS}-${ARCHNAME}"
    
            if [ "$GOOS" = "windows" ]; then
              OUT="${OUT}.exe"
            fi
    
            echo "Building $OUT"
    
            GOOS=$GOOS \
            GOARCH=$GOARCH \
            CGO_ENABLED=0 \
            go build \
              -trimpath \
              -ldflags="-s -w" \
              -o "$OUT" \
              ./ConsoleClient
          }
    
          build linux amd64 x86_64
          build linux arm64 arm64
          build linux 386 x86
          build linux arm arm
    
          build windows amd64 x86_64
          build windows arm64 arm64
          build windows 386 x86
    
          build darwin amd64 x86_64
          build darwin arm64 arm64
    
      ####################################################################
      # Checksums
      ####################################################################
    
      - name: Generate SHA256 checksums
        if: steps.release_check.outputs.exists == 'false'
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt
    
      ####################################################################
      # Generate release notes
      ####################################################################
    
      - name: Generate release notes
        if: steps.release_check.outputs.exists == 'false'
        run: |
          cat > RELEASE_NOTES.md << EOF
          Built automatically from:
    
          Repository:
          Psiphon-Labs/psiphon-tunnel-core

          Git log:
          ${{ steps.clone_upstream_repository.outputs.git_log }}
    
          Commit:
          ${{ steps.upstream.outputs.sha }}
    
          This is an unofficial automated build.
          EOF
    
      ####################################################################
      # Create GitHub Release
      ####################################################################
    
      - name: Publish Release
        if: steps.release_check.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: upstream-${{ steps.upstream.outputs.sha }}
          name: Psiphon Tunnel Core - upstream-${{ steps.upstream.outputs.short_sha }}
          body_path: RELEASE_NOTES.md
          files: |
            dist/*
